### ISSUE TITLE
Make `flake.<output>` mergeable

### ISSUE THREAD

**Issue by Mic92** [hercules-ci/flake-modules-core#12]
It's convenient to split of package sets or set of nixos systems into multiple files.
However the current type on `flake` prevent that. I cannot define nixos configurations in multiple modules:

i.e.:

- https://github.com/Mic92/dotfiles/blob/bcdeeca8e834b5629dc4960076c0cd3ca6eba969/nixos/configurations.nix
- https://github.com/Mic92/dotfiles/blob/bcdeeca8e834b5629dc4960076c0cd3ca6eba969/nixos/cloudlab.nix

**Comment by roberth** [comment]
This solution is a bit too general. I don't think we should be making assumptions about the structure of new output fields, and we don't have to because we can declare the new fields as options. That will give us precise behavior and fewer surprises like #11.
